### ISSUE TITLE
Extension not supporting full translation key

### ISSUE THREAD

**Issue by yann120** [matthizou/vscode-translation-keys-lookup#2]
Hey, 
Your extension looks amazing!
But I try to use this extension on our codebase, but it doesn't match full keys, only if there is the name of the key without the full path
Exemple : 
<img width="789" alt="Capture d’écran 2022-07-25 à 16 10 51" src="https://user-images.githubusercontent.com/10012140/180798027-8c277274-8956-4e4c-ac68-45e5f7777a79.png">
Here it's not working with the full path

<img width="444" alt="Capture d’écran 2022-07-25 à 16 11 04" src="https://user-images.githubusercontent.com/10012140/180797963-3fd60bdd-4190-4341-b5de-89935d77be7c.png">
Here it's working when I remove the full path.

It's difficult to debug because I can't find the logs in vscode

**Comment by matthizou** [comment]
Hey, 
Just seeing this message, sorry for the delay! 
How are your keys defined in your project? 

The code expects the keys to be flattened already.
In here in a `json` translation  file  that would work: 
```json
  "workspace-members.add.description": "Share",
```

This wouldn't work:
```json
  "workspace-members": {
      "add": {
          "description": "Share"
      }
  }
```

It wouldn't be hard to add support for it though (and flatten the structure above in memory).   
The load translation logic is  defined [here](https://github.com/matthizou/vscode-translation-keys-lookup/blob/main/src/loadTranslations.ts), and handling json file is literally a one-liner at the moment

**Comment by esheyw** [comment]
Just coming round to say support for unflattened keys would be very nice, as this is definitely not useful for me without it.
